services:
  db:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: "r00t"
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - bank:/database/var/lib/postgresql/data
    networks:
      - postgresql-network

networks:
  postgresql-network:
    driver: bridge

volumes:
  bank: